set echo on pause off verify on feedback on timi on autotrace off pause off lines 100
spool gfcbuild_gofaster.lst
REM Generated by GFC_PSPART - (c)Go-Faster Consultancy Ltd. www.go-faster.co.uk 2001-2011
REM GOFASTER @ 13:56:58 16.06.2011
WHENEVER SQLERROR CONTINUE



CREATE ROLE wms_update
/
CREATE ROLE wms_read_only
/

spool off
set echo on pause off verify on feedback on timi on autotrace off pause off lines 100
spool gfcbuild_gofaster_pspmeventhist.lst
REM Generated by GFC_PSPART - (c)Go-Faster Consultancy Ltd. www.go-faster.co.uk 2001-2011
REM GOFASTER @ 13:56:58 16.06.2011
WHENEVER SQLERROR CONTINUE


rem Partitioning Scheme PPMEVENT
WHENEVER SQLERROR EXIT FAILURE

WHENEVER SQLERROR CONTINUE

DROP TABLE sysadm.old_pspmeventhist PURGE
/

WHENEVER SQLERROR EXIT FAILURE

WHENEVER SQLERROR CONTINUE

ALTER TABLE sysadm.pspmeventhist RENAME PARTITION pspmeventhist_event150 TO old_pspmeventhist_event150;
ALTER TABLE sysadm.pspmeventhist RENAME PARTITION pspmeventhist_event151 TO old_pspmeventhist_event151;
ALTER TABLE sysadm.pspmeventhist RENAME PARTITION pspmeventhist_event152 TO old_pspmeventhist_event152;
ALTER TABLE sysadm.pspmeventhist RENAME PARTITION pspmeventhist_event153 TO old_pspmeventhist_event153;
ALTER TABLE sysadm.pspmeventhist RENAME PARTITION pspmeventhist_event200 TO old_pspmeventhist_event200;
ALTER TABLE sysadm.pspmeventhist RENAME PARTITION pspmeventhist_event300 TO old_pspmeventhist_event300;
ALTER TABLE sysadm.pspmeventhist RENAME PARTITION pspmeventhist_event301 TO old_pspmeventhist_event301;
ALTER TABLE sysadm.pspmeventhist RENAME PARTITION pspmeventhist_event302 TO old_pspmeventhist_event302;
ALTER TABLE sysadm.pspmeventhist RENAME PARTITION pspmeventhist_event351 TO old_pspmeventhist_event351;
ALTER TABLE sysadm.pspmeventhist RENAME PARTITION pspmeventhist_others TO old_pspmeventhist_others;

DROP INDEX psapspmeventhist;
DROP INDEX psbpspmeventhist;
DROP INDEX pscpspmeventhist;
DROP INDEX sys_il0000073438c00016$$;
WHENEVER SQLERROR EXIT FAILURE


WHENEVER SQLERROR EXIT FAILURE

CREATE TABLE sysadm.gfc_pspmeventhist
(pm_instance_id DECIMAL(20) NOT NULL
,pm_event_defn_set INTEGER NOT NULL
,pm_event_defn_id INTEGER NOT NULL
,pm_agentid DECIMAL(10) NOT NULL
,pm_agent_dttm DATE
,pm_mon_dttm DATE
,pm_process_id INTEGER NOT NULL
,pm_filter_level VARCHAR2(2) NOT NULL
,pm_metric_value1 DECIMAL(28,4) NOT NULL
,pm_metric_value2 DECIMAL(28,4) NOT NULL
,pm_metric_value3 DECIMAL(28,4) NOT NULL
,pm_metric_value4 DECIMAL(28,4) NOT NULL
,pm_metric_value5 DECIMAL(28,4) NOT NULL
,pm_metric_value6 DECIMAL(28,4) NOT NULL
,pm_metric_value7 VARCHAR2(128) NOT NULL
,pm_addtnl_descr CLOB
)
PCTFREE 10 PCTUSED 80
PARTITION BY LIST(PM_EVENT_DEFN_ID)
(PARTITION pspmeventhist_event150
 VALUES (150)
,PARTITION pspmeventhist_event151
 VALUES (151)
,PARTITION pspmeventhist_event152
 VALUES (152)
,PARTITION pspmeventhist_event153
 VALUES (153)
,PARTITION pspmeventhist_event200
 VALUES (200)
,PARTITION pspmeventhist_event300
 VALUES (300)
,PARTITION pspmeventhist_event301
 VALUES (301)
,PARTITION pspmeventhist_event302
 VALUES (302)
,PARTITION pspmeventhist_event351
 VALUES (351)
,PARTITION pspmeventhist_others
 VALUES (DEFAULT)
)
ENABLE ROW MOVEMENT
PARALLEL
NOLOGGING
/

GRANT SELECT ON sysadm.gfc_pspmeventhist TO wms_read_only
/
GRANT INSERT, UPDATE, DELETE ON sysadm.gfc_pspmeventhist TO wms_update
/

LOCK TABLE sysadm.pspmeventhist IN EXCLUSIVE MODE
/

CREATE OR REPLACE TRIGGER sysadm.pspmeventhist_nochange
BEFORE INSERT OR UPDATE OR DELETE ON sysadm.pspmeventhist
BEGIN
   RAISE_APPLICATION_ERROR(-20100,'NO DML OPERATIONS ALLOWED ON SYSADM.PSPMEVENTHIST');
END;
/

LOCK TABLE sysadm.pspmeventhist IN EXCLUSIVE MODE
/

BEGIN
INSERT /*+APPEND NOLOGGING PARALLEL(t)*/ INTO sysadm.gfc_pspmeventhist t (
pm_instance_id,pm_event_defn_set,pm_event_defn_id,pm_agentid,pm_agent_dttm,pm_mon_dttm
,pm_process_id,pm_filter_level,pm_metric_value1,pm_metric_value2,pm_metric_value3
,pm_metric_value4,pm_metric_value5,pm_metric_value6,pm_metric_value7,pm_addtnl_descr
) SELECT /*+PARALLEL(s)*/
pm_instance_id,pm_event_defn_set,pm_event_defn_id,pm_agentid,pm_agent_dttm,pm_mon_dttm
,pm_process_id,pm_filter_level,pm_metric_value1,pm_metric_value2,pm_metric_value3
,pm_metric_value4,pm_metric_value5,pm_metric_value6,pm_metric_value7,pm_addtnl_descr
FROM sysadm.pspmeventhist s;
COMMIT;
END;
/

CREATE INDEX sysadm.gfcapspmeventhist ON sysadm.gfc_pspmeventhist
(pm_agentid
,pm_event_defn_set
,pm_event_defn_id
,pm_mon_dttm
)
LOCAL
(PARTITION pspmeventhistaevent150
,PARTITION pspmeventhistaevent151
,PARTITION pspmeventhistaevent152
,PARTITION pspmeventhistaevent153
,PARTITION pspmeventhistaevent200
,PARTITION pspmeventhistaevent300
,PARTITION pspmeventhistaevent301
,PARTITION pspmeventhistaevent302
,PARTITION pspmeventhistaevent351
,PARTITION pspmeventhistaothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfcapspmeventhist
LOGGING
/
ALTER INDEX sysadm.gfcapspmeventhist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.psapspmeventhist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfcapspmeventhist RENAME TO psapspmeventhist
/

CREATE INDEX sysadm.gfcbpspmeventhist ON sysadm.gfc_pspmeventhist
(pm_agentid
,pm_event_defn_set
,pm_event_defn_id
,pm_agent_dttm
)
LOCAL
(PARTITION pspmeventhistbevent150
,PARTITION pspmeventhistbevent151
,PARTITION pspmeventhistbevent152
,PARTITION pspmeventhistbevent153
,PARTITION pspmeventhistbevent200
,PARTITION pspmeventhistbevent300
,PARTITION pspmeventhistbevent301
,PARTITION pspmeventhistbevent302
,PARTITION pspmeventhistbevent351
,PARTITION pspmeventhistbothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfcbpspmeventhist
LOGGING
/
ALTER INDEX sysadm.gfcbpspmeventhist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.psbpspmeventhist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfcbpspmeventhist RENAME TO psbpspmeventhist
/

CREATE INDEX sysadm.gfccpspmeventhist ON sysadm.gfc_pspmeventhist
(pm_agentid
,pm_filter_level
,pm_mon_dttm
)
LOCAL
(PARTITION pspmeventhistcevent150
,PARTITION pspmeventhistcevent151
,PARTITION pspmeventhistcevent152
,PARTITION pspmeventhistcevent153
,PARTITION pspmeventhistcevent200
,PARTITION pspmeventhistcevent300
,PARTITION pspmeventhistcevent301
,PARTITION pspmeventhistcevent302
,PARTITION pspmeventhistcevent351
,PARTITION pspmeventhistcothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfccpspmeventhist
LOGGING
/
ALTER INDEX sysadm.gfccpspmeventhist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.pscpspmeventhist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfccpspmeventhist RENAME TO pscpspmeventhist
/

CREATE UNIQUE INDEX sysadm.gfc_pspmeventhist ON sysadm.gfc_pspmeventhist
(pm_instance_id
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfc_pspmeventhist
LOGGING
/
ALTER INDEX sysadm.gfc_pspmeventhist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.ps_pspmeventhist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfc_pspmeventhist RENAME TO ps_pspmeventhist
/

WHENEVER SQLERROR EXIT FAILURE

ALTER TABLE sysadm.gfc_pspmeventhist LOGGING NOPARALLEL MONITORING
/
WHENEVER SQLERROR CONTINUE

ALTER TABLE sysadm.pspmeventhist RENAME TO old_pspmeventhist
/

WHENEVER SQLERROR EXIT FAILURE

ALTER TABLE sysadm.gfc_pspmeventhist RENAME TO pspmeventhist
/

WHENEVER SQLERROR CONTINUE

DROP TABLE sysadm.old_pspmeventhist PURGE
/

DROP TRIGGER sysadm.pspmeventhist_nochange
/

spool off
set echo on pause off verify on feedback on timi on autotrace off pause off lines 100
spool gfcbuild_gofaster_pspmtranshist.lst
REM Generated by GFC_PSPART - (c)Go-Faster Consultancy Ltd. www.go-faster.co.uk 2001-2011
REM GOFASTER @ 13:56:59 16.06.2011
WHENEVER SQLERROR CONTINUE


rem Partitioning Scheme PPMTRANS
WHENEVER SQLERROR EXIT FAILURE

WHENEVER SQLERROR CONTINUE

DROP TABLE sysadm.old_pspmtranshist PURGE
/

WHENEVER SQLERROR EXIT FAILURE

WHENEVER SQLERROR CONTINUE

ALTER TABLE sysadm.pspmtranshist RENAME PARTITION pspmtranshist_others TO old_pspmtranshist_others;

DROP INDEX psapspmtranshist;
DROP INDEX psbpspmtranshist;
DROP INDEX pscpspmtranshist;
DROP INDEX psdpspmtranshist;
DROP INDEX psepspmtranshist;
DROP INDEX psfpspmtranshist;
DROP INDEX psgpspmtranshist;
DROP INDEX psjpspmtranshist;
DROP INDEX pskpspmtranshist;
DROP INDEX pslpspmtranshist;
DROP INDEX psmpspmtranshist;
DROP INDEX psnpspmtranshist;
DROP INDEX psopspmtranshist;
DROP INDEX sys_il0000073355c00027$$;
WHENEVER SQLERROR EXIT FAILURE


WHENEVER SQLERROR EXIT FAILURE

CREATE TABLE sysadm.gfc_pspmtranshist
(pm_instance_id DECIMAL(20) NOT NULL
,pm_trans_defn_set INTEGER NOT NULL
,pm_trans_defn_id INTEGER NOT NULL
,pm_agentid DECIMAL(10) NOT NULL
,pm_trans_status VARCHAR2(1) NOT NULL
,oprid VARCHAR2(30) NOT NULL
,pm_perf_trace VARCHAR2(30) NOT NULL
,pm_context_value1 VARCHAR2(254) NOT NULL
,pm_context_value2 VARCHAR2(254) NOT NULL
,pm_context_value3 VARCHAR2(254) NOT NULL
,pm_contextid_1 INTEGER NOT NULL
,pm_contextid_2 INTEGER NOT NULL
,pm_contextid_3 INTEGER NOT NULL
,pm_process_id INTEGER NOT NULL
,pm_agent_strt_dttm DATE
,pm_mon_strt_dttm DATE
,pm_trans_duration DECIMAL(21,3) NOT NULL
,pm_parent_inst_id DECIMAL(20) NOT NULL
,pm_top_inst_id DECIMAL(20) NOT NULL
,pm_metric_value1 DECIMAL(28,4) NOT NULL
,pm_metric_value2 DECIMAL(28,4) NOT NULL
,pm_metric_value3 DECIMAL(28,4) NOT NULL
,pm_metric_value4 DECIMAL(28,4) NOT NULL
,pm_metric_value5 DECIMAL(28,4) NOT NULL
,pm_metric_value6 DECIMAL(28,4) NOT NULL
,pm_metric_value7 VARCHAR2(128) NOT NULL
,pm_addtnl_descr CLOB
)
PCTFREE 10 PCTUSED 80
PARTITION BY LIST(PM_TRANS_DEFN_ID)
(PARTITION pspmtranshist_trans101
 VALUES (101)
,PARTITION pspmtranshist_trans108
 VALUES (108)
,PARTITION pspmtranshist_trans109
 VALUES (109)
,PARTITION pspmtranshist_trans113
 VALUES (113)
,PARTITION pspmtranshist_trans412
 VALUES (115)
,PARTITION pspmtranshist_trans116
 VALUES (116)
,PARTITION pspmtranshist_trans400
 VALUES (400)
,PARTITION pspmtranshist_trans401
 VALUES (401)
,PARTITION pspmtranshist_others
 VALUES (DEFAULT)
)
ENABLE ROW MOVEMENT
PARALLEL
NOLOGGING
/

GRANT SELECT ON sysadm.gfc_pspmtranshist TO wms_read_only
/
GRANT INSERT, UPDATE, DELETE ON sysadm.gfc_pspmtranshist TO wms_update
/

LOCK TABLE sysadm.pspmtranshist IN EXCLUSIVE MODE
/

CREATE OR REPLACE TRIGGER sysadm.pspmtranshist_nochange
BEFORE INSERT OR UPDATE OR DELETE ON sysadm.pspmtranshist
BEGIN
   RAISE_APPLICATION_ERROR(-20100,'NO DML OPERATIONS ALLOWED ON SYSADM.PSPMTRANSHIST');
END;
/

LOCK TABLE sysadm.pspmtranshist IN EXCLUSIVE MODE
/

BEGIN
INSERT /*+APPEND NOLOGGING PARALLEL(t)*/ INTO sysadm.gfc_pspmtranshist t (
pm_instance_id,pm_trans_defn_set,pm_trans_defn_id,pm_agentid,pm_trans_status,oprid
,pm_perf_trace,pm_context_value1,pm_context_value2,pm_context_value3,pm_contextid_1
,pm_contextid_2,pm_contextid_3,pm_process_id,pm_agent_strt_dttm,pm_mon_strt_dttm
,pm_trans_duration,pm_parent_inst_id,pm_top_inst_id,pm_metric_value1,pm_metric_value2
,pm_metric_value3,pm_metric_value4,pm_metric_value5,pm_metric_value6,pm_metric_value7
,pm_addtnl_descr
) SELECT /*+PARALLEL(s)*/
pm_instance_id,pm_trans_defn_set,pm_trans_defn_id,pm_agentid,pm_trans_status,oprid
,pm_perf_trace,pm_context_value1,pm_context_value2,pm_context_value3,pm_contextid_1
,pm_contextid_2,pm_contextid_3,pm_process_id,pm_agent_strt_dttm,pm_mon_strt_dttm
,pm_trans_duration,pm_parent_inst_id,pm_top_inst_id,pm_metric_value1,pm_metric_value2
,pm_metric_value3,pm_metric_value4,pm_metric_value5,pm_metric_value6,pm_metric_value7
,pm_addtnl_descr
FROM sysadm.pspmtranshist s;
COMMIT;
END;
/

CREATE INDEX sysadm.gfcapspmtranshist ON sysadm.gfc_pspmtranshist
(pm_trans_defn_set
,pm_trans_defn_id
,pm_agentid
,pm_mon_strt_dttm
)
LOCAL
(PARTITION pspmtranshistatrans101
,PARTITION pspmtranshistatrans108
,PARTITION pspmtranshistatrans109
,PARTITION pspmtranshistatrans113
,PARTITION pspmtranshistatrans412
,PARTITION pspmtranshistatrans116
,PARTITION pspmtranshistatrans400
,PARTITION pspmtranshistatrans401
,PARTITION pspmtranshistaothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfcapspmtranshist
LOGGING
/
ALTER INDEX sysadm.gfcapspmtranshist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.psapspmtranshist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfcapspmtranshist RENAME TO psapspmtranshist
/

CREATE INDEX sysadm.gfcbpspmtranshist ON sysadm.gfc_pspmtranshist
(oprid
,pm_agentid
,pm_mon_strt_dttm
)
LOCAL
(PARTITION pspmtranshistbtrans101
,PARTITION pspmtranshistbtrans108
,PARTITION pspmtranshistbtrans109
,PARTITION pspmtranshistbtrans113
,PARTITION pspmtranshistbtrans412
,PARTITION pspmtranshistbtrans116
,PARTITION pspmtranshistbtrans400
,PARTITION pspmtranshistbtrans401
,PARTITION pspmtranshistbothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfcbpspmtranshist
LOGGING
/
ALTER INDEX sysadm.gfcbpspmtranshist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.psbpspmtranshist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfcbpspmtranshist RENAME TO psbpspmtranshist
/

CREATE INDEX sysadm.gfccpspmtranshist ON sysadm.gfc_pspmtranshist
(pm_perf_trace
,pm_mon_strt_dttm
)
LOCAL
(PARTITION pspmtranshistctrans101
,PARTITION pspmtranshistctrans108
,PARTITION pspmtranshistctrans109
,PARTITION pspmtranshistctrans113
,PARTITION pspmtranshistctrans412
,PARTITION pspmtranshistctrans116
,PARTITION pspmtranshistctrans400
,PARTITION pspmtranshistctrans401
,PARTITION pspmtranshistcothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfccpspmtranshist
LOGGING
/
ALTER INDEX sysadm.gfccpspmtranshist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.pscpspmtranshist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfccpspmtranshist RENAME TO pscpspmtranshist
/

CREATE INDEX sysadm.gfcdpspmtranshist ON sysadm.gfc_pspmtranshist
(pm_top_inst_id
)
LOCAL
(PARTITION pspmtranshistdtrans101
,PARTITION pspmtranshistdtrans108
,PARTITION pspmtranshistdtrans109
,PARTITION pspmtranshistdtrans113
,PARTITION pspmtranshistdtrans412
,PARTITION pspmtranshistdtrans116
,PARTITION pspmtranshistdtrans400
,PARTITION pspmtranshistdtrans401
,PARTITION pspmtranshistdothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfcdpspmtranshist
LOGGING
/
ALTER INDEX sysadm.gfcdpspmtranshist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.psdpspmtranshist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfcdpspmtranshist RENAME TO psdpspmtranshist
/

CREATE INDEX sysadm.gfcepspmtranshist ON sysadm.gfc_pspmtranshist
(pm_context_value1
,pm_agentid
,pm_mon_strt_dttm
)
LOCAL
(PARTITION pspmtranshistetrans101
,PARTITION pspmtranshistetrans108
,PARTITION pspmtranshistetrans109
,PARTITION pspmtranshistetrans113
,PARTITION pspmtranshistetrans412
,PARTITION pspmtranshistetrans116
,PARTITION pspmtranshistetrans400
,PARTITION pspmtranshistetrans401
,PARTITION pspmtranshisteothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfcepspmtranshist
LOGGING
/
ALTER INDEX sysadm.gfcepspmtranshist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.psepspmtranshist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfcepspmtranshist RENAME TO psepspmtranshist
/

CREATE INDEX sysadm.gfcfpspmtranshist ON sysadm.gfc_pspmtranshist
(pm_context_value2
,pm_agentid
,pm_mon_strt_dttm
)
LOCAL
(PARTITION pspmtranshistftrans101
,PARTITION pspmtranshistftrans108
,PARTITION pspmtranshistftrans109
,PARTITION pspmtranshistftrans113
,PARTITION pspmtranshistftrans412
,PARTITION pspmtranshistftrans116
,PARTITION pspmtranshistftrans400
,PARTITION pspmtranshistftrans401
,PARTITION pspmtranshistfothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfcfpspmtranshist
LOGGING
/
ALTER INDEX sysadm.gfcfpspmtranshist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.psfpspmtranshist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfcfpspmtranshist RENAME TO psfpspmtranshist
/

CREATE INDEX sysadm.gfcgpspmtranshist ON sysadm.gfc_pspmtranshist
(pm_agentid
,pm_mon_strt_dttm
,pm_trans_duration
)
LOCAL
(PARTITION pspmtranshistgtrans101
,PARTITION pspmtranshistgtrans108
,PARTITION pspmtranshistgtrans109
,PARTITION pspmtranshistgtrans113
,PARTITION pspmtranshistgtrans412
,PARTITION pspmtranshistgtrans116
,PARTITION pspmtranshistgtrans400
,PARTITION pspmtranshistgtrans401
,PARTITION pspmtranshistgothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfcgpspmtranshist
LOGGING
/
ALTER INDEX sysadm.gfcgpspmtranshist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.psgpspmtranshist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfcgpspmtranshist RENAME TO psgpspmtranshist
/

CREATE INDEX sysadm.gfcjpspmtranshist ON sysadm.gfc_pspmtranshist
(pm_parent_inst_id
)
LOCAL
(PARTITION pspmtranshistjtrans101
,PARTITION pspmtranshistjtrans108
,PARTITION pspmtranshistjtrans109
,PARTITION pspmtranshistjtrans113
,PARTITION pspmtranshistjtrans412
,PARTITION pspmtranshistjtrans116
,PARTITION pspmtranshistjtrans400
,PARTITION pspmtranshistjtrans401
,PARTITION pspmtranshistjothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfcjpspmtranshist
LOGGING
/
ALTER INDEX sysadm.gfcjpspmtranshist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.psjpspmtranshist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfcjpspmtranshist RENAME TO psjpspmtranshist
/

CREATE INDEX sysadm.gfckpspmtranshist ON sysadm.gfc_pspmtranshist
(pm_trans_defn_id
)
LOCAL
(PARTITION pspmtranshistktrans101
,PARTITION pspmtranshistktrans108
,PARTITION pspmtranshistktrans109
,PARTITION pspmtranshistktrans113
,PARTITION pspmtranshistktrans412
,PARTITION pspmtranshistktrans116
,PARTITION pspmtranshistktrans400
,PARTITION pspmtranshistktrans401
,PARTITION pspmtranshistkothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfckpspmtranshist
LOGGING
/
ALTER INDEX sysadm.gfckpspmtranshist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.pskpspmtranshist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfckpspmtranshist RENAME TO pskpspmtranshist
/

CREATE INDEX sysadm.gfclpspmtranshist ON sysadm.gfc_pspmtranshist
(pm_perf_trace
)
LOCAL
(PARTITION pspmtranshistltrans101
,PARTITION pspmtranshistltrans108
,PARTITION pspmtranshistltrans109
,PARTITION pspmtranshistltrans113
,PARTITION pspmtranshistltrans412
,PARTITION pspmtranshistltrans116
,PARTITION pspmtranshistltrans400
,PARTITION pspmtranshistltrans401
,PARTITION pspmtranshistlothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfclpspmtranshist
LOGGING
/
ALTER INDEX sysadm.gfclpspmtranshist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.pslpspmtranshist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfclpspmtranshist RENAME TO pslpspmtranshist
/

CREATE INDEX sysadm.gfcmpspmtranshist ON sysadm.gfc_pspmtranshist
(pm_agentid
)
LOCAL
(PARTITION pspmtranshistmtrans101
,PARTITION pspmtranshistmtrans108
,PARTITION pspmtranshistmtrans109
,PARTITION pspmtranshistmtrans113
,PARTITION pspmtranshistmtrans412
,PARTITION pspmtranshistmtrans116
,PARTITION pspmtranshistmtrans400
,PARTITION pspmtranshistmtrans401
,PARTITION pspmtranshistmothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfcmpspmtranshist
LOGGING
/
ALTER INDEX sysadm.gfcmpspmtranshist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.psmpspmtranshist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfcmpspmtranshist RENAME TO psmpspmtranshist
/

CREATE INDEX sysadm.gfcnpspmtranshist ON sysadm.gfc_pspmtranshist
(pm_process_id
)
LOCAL
(PARTITION pspmtranshistntrans101
,PARTITION pspmtranshistntrans108
,PARTITION pspmtranshistntrans109
,PARTITION pspmtranshistntrans113
,PARTITION pspmtranshistntrans412
,PARTITION pspmtranshistntrans116
,PARTITION pspmtranshistntrans400
,PARTITION pspmtranshistntrans401
,PARTITION pspmtranshistnothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfcnpspmtranshist
LOGGING
/
ALTER INDEX sysadm.gfcnpspmtranshist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.psnpspmtranshist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfcnpspmtranshist RENAME TO psnpspmtranshist
/

CREATE INDEX sysadm.gfcopspmtranshist ON sysadm.gfc_pspmtranshist
(pm_trans_defn_id
,pm_context_value1
,pm_context_value2
,pm_metric_value1
,pm_metric_value7
,pm_agent_strt_dttm
)
LOCAL
(PARTITION pspmtranshistotrans101
,PARTITION pspmtranshistotrans108
,PARTITION pspmtranshistotrans109
,PARTITION pspmtranshistotrans113
,PARTITION pspmtranshistotrans412
,PARTITION pspmtranshistotrans116
,PARTITION pspmtranshistotrans400
,PARTITION pspmtranshistotrans401
,PARTITION pspmtranshistoothers
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfcopspmtranshist
LOGGING
/
ALTER INDEX sysadm.gfcopspmtranshist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.psopspmtranshist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfcopspmtranshist RENAME TO psopspmtranshist
/

CREATE UNIQUE INDEX sysadm.gfc_pspmtranshist ON sysadm.gfc_pspmtranshist
(pm_instance_id
)
PCTFREE 10
PARALLEL
NOLOGGING
/

ALTER INDEX sysadm.gfc_pspmtranshist
LOGGING
/
ALTER INDEX sysadm.gfc_pspmtranshist
NOPARALLEL
/

WHENEVER SQLERROR CONTINUE

DROP INDEX sysadm.ps_pspmtranshist
/
WHENEVER SQLERROR EXIT FAILURE

ALTER INDEX sysadm.gfc_pspmtranshist RENAME TO ps_pspmtranshist
/

WHENEVER SQLERROR EXIT FAILURE

ALTER TABLE sysadm.gfc_pspmtranshist LOGGING NOPARALLEL MONITORING
/
WHENEVER SQLERROR CONTINUE

ALTER TABLE sysadm.pspmtranshist RENAME TO old_pspmtranshist
/

WHENEVER SQLERROR EXIT FAILURE

ALTER TABLE sysadm.gfc_pspmtranshist RENAME TO pspmtranshist
/

WHENEVER SQLERROR CONTINUE

DROP TABLE sysadm.old_pspmtranshist PURGE
/

DROP TRIGGER sysadm.pspmtranshist_nochange
/

spool off
